{% set name = "python-xz" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c8dc51070799ee9e77ddd9dd207a11cc9170e9298542f81e7187072e0d543478

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}

test:
  imports:
    - xz
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/rogdham/python-xz
  summary: Pure Python implementation of the XZ file format with random access support
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ap--
